### ISSUE TITLE
Program crashes after I select a model

### ISSUE THREAD

**Issue by bananaman08** [Babyhamsta/Aimmy#49] opened 2023-11-01 20:04 UTC
![image_2023-11-01_220415409](https://github.com/Babyhamsta/Aimmy/assets/105743921/51b9f50e-198f-4943-aa5c-31e3c9ff3015)

**Comment by Babyhamsta** [comment] 2023-11-01 20:33
Duplicate of https://github.com/Babyhamsta/Aimmy/issues/18, https://github.com/Babyhamsta/Aimmy/issues/32, https://github.com/Babyhamsta/Aimmy/issues/39, and https://github.com/Babyhamsta/Aimmy/issues/41

**Comment by scriptedradio** [comment] 2023-11-21 06:38
Is there a fix for it?

**Closed** 2023-12-18 14:49 UTC
Labels: bug, duplicate
