### ISSUE TITLE
TPS Fov possiblity

### ISSUE THREAD

**Issue by TONNNoor** [Babyhamsta/Aimmy#53] opened 2023-11-08 23:54 UTC
I just would like to ask is it possible to add a TPS fov for a moving mouse for another kind of shooter games?
just to add a new tab where you can enable it or disable it or does the models consider this? like is it possible for it to happen if someone makes a TPS MODEL? for example like a hitbox expander

**Comment by Babyhamsta** [comment] 2023-11-25 18:48
Duplicate of https://github.com/Babyhamsta/Aimmy/issues/9

**Closed by Babyhamsta** 2023-11-25 18:48 UTC
Labels: duplicate, enhancement
